### PR TITLE
Pull upstream

### PR DESCRIPTION
**Pull request by TacoTheDank**
(Couldn't create the pull request directly from gabrielecirulli's repo, so I had to fork it and do this.)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@uberspot You should check all the commits to make sure they're satisfactory, though the last one is actually the most important :)

**Comment by uberspot** [comment]
Nice :+1: merged :)

**Comment by TacoTheDank** [comment]
😀

**Comment by uberspot** [comment]
Sweet, I can review whenever you have it. :+1:

**Pull request merged**
