### PR TITLE
Backported changes to main.css into main.scss and made corrections.

### PR DESCRIPTION
**Pull request by anthonykozar**
Hello!

When the undo functionality was added, it included a main.css file that was hand edited.  I have ported those changes back into the main.scss Sass file to improve maintainability.  I also corrected some problems in the Sass code that were producing errors in the CSS output when I regenerated it.  (I'm not really sure how the Sass code was working before unless earlier versions were more lax!)  Finally, I added a couple of files to .gitignore that make things easier (at least for me :).

As far as I know, these changes do not affect the functionality of the game at all.  I tried to make the output of the Sass code correspond to the old CSS file as much as was reasonable.

Anthony

### CODE REVIEW

**Comment by uberspot** [comment]
This is great! :) Could you briefly provide a screenshot of the result? Just for confirmation. Otherwise It might take a bit more to build/test. Also we'll need another PR on 2048-android to point it to the newer commit.

**Comment by anthonykozar** [comment]
OK.  I rebuilt the android app and tried it on my phone.  A screenshot is attached.  I didn't find  any problems during my brief test.

Screenshot_20190328-172657

I don't fully understand how the 2048 repository functions as a submodule of the 2048-android repository.  (My knowledge of Git is not that advanced).  Am I supposed to checkout the specific commit in 2048 (so that the HEAD is detached) and then do a commit in 2048-android??  I'll try to do some research to get a better understanding.

Glad that you are interested in these changes! :)

**Comment by uberspot** [comment]
Merged :+1:

**Comment by anthonykozar** [comment]
Cool. Thanks.

I noticed that GitHub snuck an extra commit into the pull request yesterday that I had not intended.  Sorry!  I didn't know that it would add further commits from my master branch to the pull request.  Fortunately, they were changes that I intended to submit to you in another PR.  Here's a description so that you can decide whether to keep that commit (#99a6d212bb... titled "Improve layout for very small screens (320x480) and avoid layout changes with scores above 100,000 points.")

When the score in 2048 goes above 100,000, the score boxes become too wide and they get bumped down below the "2048" header.  This shifts the entire layout down and looks awkward.  On the smallest screens (like 320x480), in which the bottom edge of the game was already cut off a little, this layout change with high scores causes the last row of tiles to move offscreen.  (It is possible to scroll the web view but it is too tall now to all fit).  The screenshots below show a before and after for the layout changes that I made.  I hope that you decide to keep them.  :)

2048-current-with-high score

2048-improved-with-high score

**Comment by uberspot** [comment]
It actually looks much better. Thanks for that. :)

**Pull request merged**
