### PR TITLE
Undo feature

### PR DESCRIPTION
**Pull request by fraggerfox**
Hello

I added an undo feature to the 2048 game, now users are able to undo from a given state until the original start state of the game.

-- Santhosh

### CODE REVIEW

**Comment by uberspot** [comment]
Cool! :) thank you
I don't know if the undo is a much wanted feature from users but I'll merge it for now and if I head complains I'll revert it.

**Comment by uberspot** [comment]
I've had mails from users that the game becomes painfully slow after some point (after reaching 16384 for example). And this appeared after the undo button was added. 
Could you make a new pull request where the stack keeps only the last ~50 states for example and clears the rest while running? 
It's basically an if clause in LocalStorageManager.prototype.pushGameState that checks if the num of states is >50 then it pops the very first state added (a queue might be more suited here).

**Comment by fraggerfox** [comment]
Yes, I can do that, will do the changes and notify you.

**Comment by fraggerfox** [comment]
Created a new pull request.

Kindly review.

**Pull request merged**
